name: CSE 30 Fall 2016
github_url: https://github.com/ucsd-cse30-fall-2016/ucsd-cse30-fall-2016.github.io
mentor_url: mentor.html

url: https://ucsd-cse30-fall-2016.github.io/

piazza: https://piazza.com/class/isulbhfp4er74o#
gradescope: https://gradescope.com/courses/4118

weekly_google_calendar_prefix: "https://sites.google.com/a/eng.ucsd.edu/spis/home/AcademicProgram/2016-foundations#week"

google_calendar_embed: "https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffff99&amp;src=eng.ucsd.edu_rg7770j4sj2i20n8t6i6b51aks%40group.calendar.google.com&amp;color=%23705770&amp;ctz=America%2FLos_Angeles"

google_calendar_embed_height_600px: "https://calendar.google.com/calendar/embed?mode=WEEK&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=eng.ucsd.edu_rg7770j4sj2i20n8t6i6b51aks%40group.calendar.google.com&amp;color=%2328754E&amp;ctz=America%2FLos_Angeles"
course_github_url: https://github.com/ucsd-cse30-fall-2016

guttag_url: "https://mitpress.mit.edu/books/introduction-computation-and-programming-using-python-0"

num_weeks: 11
start_date: 2016-09-18 00:00:00.00-7:00

hwk_course: "CSE 30"
course: "CSE 30: Computer Organization and Systems Programming"
year: "Fall 2016"

kramdown:
   parse_block_html: true

exclude: [vendor]

timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
    last_before: false
  quiz:
    output: true
    permalink: /quiz/:path/
    last_before: false
  info:
    output: true
    permalink: /info/:path/
  topics:
    output: true
    permalink: /topics/:path/
  lectures:
    output: true
    permalink: /lectures/:path/
  staff:
    output: true
    permalink: /mentor/:path/
  instructor:
    output: true
    permalink: /instructor/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab

  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam 
  - 
    scope:
      path: ""
      type: quiz 
    values:
      layout: quiz 
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
